spring.application.name=grocery-api
# Server config
server.port=8080

# Log or display messages
spring.application.name=grocery-api


spring.security.user.name=admin
spring.security.user.password=admin
spring.security.enabled=false
